{% set version = "3.4.0" %}

package:
  name: vega
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/v/vega/vega-{{ version }}.tar.gz
  sha256: f343ceb11add58d24cd320d69e410b111a56c98c9069ebb4ef89c608c4c1950d

build:
  number: 0
  skip: true  # [py<36]
  script:
    - rm -f pyproject.toml
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - poetry >=0.12
  run:
    - python
    - jupyter >=1.0.0,<2.0.0
    - pandas >=1.0.0,<2.0.0

test:
  imports:
    - vega

about:
  home: https://github.com/vega/ipyvega
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A Jupyter widget for Vega 5 and Vega-Lite 4

extra:
  recipe-maintainers:
    - jakevdp
    - ellisonbg
    - domoritz
    - ocefpaf
