{% set version = "3.2.0" %}

package:
  name: vega
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/v/vega/vega-{{ version }}.tar.gz
  sha256: c22f090ea9a0c84b8d6399a3a1fc11e4e1ea38817b8ccf9a75bfee24cd1a5edd

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - poetry >=0.12
  run:
    - python
    - jupyter >=1.0.0,<2.0.0
    - pandas >=1.0.0,<2.0.0

test:
  imports:
    - vega

about:
  home: https://github.com/vega/ipyvega
  license: BSD-3-Clause
  license_file: LICENSE
  summary: An IPython/Jupyter widget for Vega and Vega-Lite

extra:
  recipe-maintainers:
    - jakevdp
    - ellisonbg
    - domoritz
    - ocefpaf
