appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: JSZOnpPaS6GDRNQB6PzLurqVqKtTxsYA5MDJy7zphK6jgKCijKtNwnzpMoGtSNiETnzMiTNmheGrMhwAcyfkv2q37q0dQ6iZwmjIdYSyIOWeZv+6NkcLTJFbbZfm7ib7irKoYRkfZJ8m71SIXLJOGCx9MxS5lJ9WfF86A47xLd0judZpAQHqLRJWHQ3biQE+0bzTCMfTtlmNrz1B5vG/GNbdHoJIwRJ8YrBfAl9Ep6zR03poiBoG2ykp1vUOJ3owl4q/RunxMmCUSRp0Moqi+Zi+J9B2BYqRgsEcmcqDODiaNtaIIF6uz7UqzIZL6euC+kNqqVJeOk+lOphyE3m4105RXfvv3XNSMtbLAtdKOVHmoY+OscAtb7nYdABRDoyiEpQLNhBQKOIRQN1D4zaAV1GAGXvWeHFWqdZ++4YLeIbifAwkVJi/4bzDjdk1wG6kYhpX8g9xOlMUSRSyb/n1AhDRLoLBBLHO+nU7M7URocT16odEO4j69uMVUKBgODeS+x78peZtGNhAwnplNN+ayfX3+tajlV7/WsS7C1NAbyBiG7oEuhr7WQGiaM+0fg2iICLS8Yzx9yNtv05EHzgNu19K2dMGZErYDWI/SEajNiact43YnOmn1ZSc5T6dizPFUuGHmsxhT1GXIClokWoNr2zKAuFdFlNJyLR2uDsUWyI=}
provider:
  win: azure
conda_forge_output_validation: true
